# Stage 1 - build the Vite app
FROM node:20-alpine AS builder
WORKDIR /app

# Build arguments for Vite env variables
ARG VITE_AI_PROVIDER=gemini
ARG VITE_GEMINI_API_KEY
ARG VITE_OPENAI_API_KEY
ARG VITE_OPENAI_MODEL
ARG VITE_OPENAI_MODEL_THINKING
ARG VITE_ANTHROPIC_API_KEY
ARG VITE_ANTHROPIC_MODEL
ARG VITE_ANTHROPIC_MODEL_THINKING
ARG VITE_GOOGLE_MAPS_API_KEY
ARG REACT_APP_GOOGLE_MAPS_API_KEY

ENV VITE_AI_PROVIDER=${VITE_AI_PROVIDER} \
    VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY} \
    VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY} \
    VITE_OPENAI_MODEL=${VITE_OPENAI_MODEL} \
    VITE_OPENAI_MODEL_THINKING=${VITE_OPENAI_MODEL_THINKING} \
    VITE_ANTHROPIC_API_KEY=${VITE_ANTHROPIC_API_KEY} \
    VITE_ANTHROPIC_MODEL=${VITE_ANTHROPIC_MODEL} \
    VITE_ANTHROPIC_MODEL_THINKING=${VITE_ANTHROPIC_MODEL_THINKING} \
    VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY} \
    REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2 - serve static assets with Nginx
FROM nginx:1.27-alpine AS runner
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
